;METADATA=(Diff=true, UseCommands=true)
[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagRedirects=(OldTagName="BPAS.Event.CheckHasLanded",NewTagName="BPAS.Event.HasLanded")
+GameplayTagList=(Tag="BPAS.Ability.General.Jump",DevComment="")
+GameplayTagList=(Tag="BPAS.Ability.General.Sprint",DevComment="")
+GameplayTagList=(Tag="BPAS.Attribute.Health",DevComment="")
+GameplayTagList=(Tag="BPAS.Attribute.Stamina",DevComment="")
+GameplayTagList=(Tag="BPAS.Event.CheckHasCombo",DevComment="")
+GameplayTagList=(Tag="BPAS.Event.HasLanded",DevComment="")
+GameplayTagList=(Tag="BPAS.Event.ResetCombo",DevComment="")
+GameplayTagList=(Tag="State.Character.Main.Armed",DevComment="")
+GameplayTagList=(Tag="State.Character.Main.Unarmed",DevComment="")
+GameplayTagList=(Tag="State.Character.Secondary.Jumping",DevComment="")
+GameplayTagList=(Tag="State.Character.Secondary.Sprinting",DevComment="")

